action_list:

  number_of_targets: 8

  action_0:
    action_type: pose    
    translation: [0.3, 0.0, 0.35]
    orientation: [0.0, 0.0, 1.5]
    duration: 3.0
     
  action_1:
    action_type: pose    
    translation: [0.3, -0.3, 0.35 ]
    orientation: [0, 0.0, 1.5]
    duration: 1.0
     
  action_2:
    action_type: pose    
    translation: [ 0.3, -0.1, 0.4]
    orientation: [ 0.0, 0.0, 1.5]
    duration: 3.0
    
  action_3:
    action_type: pose    
    translation: [ 0.4, -0.05, 0.35]
    orientation: [ 0.0, 0.0, 1.5]
    duration: 3.0
   
  action_4:
    action_type: pose    
    translation: [ 0.4, -0.3, 0.35]
    orientation: [ 0.0, 0.0, 1.5]
    duration: 1.0
 
  action_5:
    action_type: pose    
    translation: [ 0.3, 0.1, 0.4]
    orientation: [ 0.0, 0.0, 1.5]
    duration: 3.0
    
  action_6:
    action_type: pose    
    translation: [ 0.4, 0.2, 0.35]
    orientation: [ 0.0, 0.0, 1.5]
    duration: 3.0

  action_7:
    action_type: pose    
    translation: [ 0.4, -0.3, 0.35]
    orientation: [ 0.0, 0.0, 1.5]
    duration: 1.0


